# LISTA 10 - NUMPY (VERSIÓN SIMPLIFICADA)

## Ejercicios sobre operaciones básicas con NumPy

**Nota:** Estos ejercicios están simplificados para enfocarse en conceptos esenciales.
- Crear arrays
- Indexing y slicing
- Operaciones aritméticas
- Funciones estadísticas

In [1]:
import numpy as np

---

## Ejercicio 1: Crear y manipular arrays

1.1) Crea un array con números del 1 al 10

In [2]:
# Tu código aquí
# Usa np.arange(1, 11)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

1.2) Crea un array de 5 elementos con todos los valores igual a 0

In [4]:
# Tu código aquí
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

1.3) Crea un array de 3 elementos con todos los valores igual a 1

In [5]:
# Tu código aquí
np.ones(3, dtype=int)

array([1, 1, 1])

---

## Ejercicio 2: Indexing y Slicing

Dado este array:

In [6]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(f"Array: {arr}")

Array: [10 20 30 40 50 60 70 80]


2.1) Obtén el primer elemento

In [7]:
# Tu código aquí
arr[0]

np.int64(10)

2.2) Obtén el último elemento

In [8]:
# Tu código aquí
arr[-1]

np.int64(80)

2.3) Obtén los elementos del índice 2 al 5 (inclusive)

In [11]:
# Tu código aquí
arr[1:5]

array([20, 30, 40, 50])

2.4) Obtén cada segundo elemento (índices 0, 2, 4, 6...)

In [13]:
# Tu código aquí
for i in range(1,len(arr)+1):
    if not i % 2:
        print(arr[i-1])

20
40
60
80


---

## Ejercicio 3: Operaciones aritméticas

Dado estos arrays:

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(f"a = {a}")
print(f"b = {b}")

a = [1 2 3 4]
b = [10 20 30 40]


3.1) Suma elemento a elemento

In [15]:
# Tu código aquí
a + b

array([11, 22, 33, 44])

3.2) Multiplica 'a' por 5

In [16]:
# Tu código aquí
a * 5

array([ 5, 10, 15, 20])

3.3) Divide 'b' entre 10

In [17]:
# Tu código aquí
b/10

array([1., 2., 3., 4.])

---

## Ejercicio 4: Funciones estadísticas

Dado este array de datos de ventas:

In [18]:
ventas = np.array([100, 150, 120, 200, 180, 220, 150, 190])
print(f"Ventas: {ventas}")

Ventas: [100 150 120 200 180 220 150 190]


4.1) Calcula la suma total de ventas

In [21]:
# Tu código aquí
ventas.sum()

np.int64(1310)

4.2) Calcula el promedio de ventas

In [22]:
# Tu código aquí
ventas.mean()

np.float64(163.75)

4.3) Encuentra la venta mínima y máxima

In [24]:
# Tu código aquí
print(ventas.min())
print(ventas.max())

100
220


---

## Ejercicio 5: Casos prácticos

5.1) **Aumento de salarios:** 
- Array de salarios actuales: [2000, 2500, 3000, 1800, 2200]
- Calcula los nuevos salarios con un aumento del 10%

In [27]:
salarios_actuales = np.array([2000, 2500, 3000, 1800, 2200])

# Tu código aquí
# Incrementa 10% (multiplica por 1.10)
nuevos_salarios = salarios_actuales * 1.1
print(nuevos_salarios)

[2200. 2750. 3300. 1980. 2420.]


5.2) **Conversión de temperatura:**
- Array de temperaturas en Celsius: [0, 15, 30, 45]
- Convierte a Fahrenheit usando la fórmula: F = C * 9/5 + 32

In [28]:
celsius = np.array([0, 15, 30, 45])

# Tu código aquí

fahrenheit = celsius * (9/5) + 32
print(fahrenheit)

[ 32.  59.  86. 113.]


5.3) **Selección de valores altos:**
- Array de calificaciones: [65, 78, 92, 55, 88, 76]
- Cuenta cuántas calificaciones son mayores a 80

In [30]:
calificaciones = np.array([65, 78, 92, 55, 88, 76])

# Tu código aquí

mayores_ochenta = calificaciones[calificaciones > 80]
print(len(mayores_ochenta))

2
